-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.sellers
(
    seller_id bigserial NOT NULL,
    name character varying(255) NOT NULL,
    photo_url character varying(150) NOT NULL,
    about_me text,
    "Adress1" character varying(255) NOT NULL,
    "Adress2" character varying(255) NOT NULL,
    city character varying(50) NOT NULL,
    state character varying(50) NOT NULL,
    country character varying(50) NOT NULL,
    zip_code character varying(20) NOT NULL,
    phone_number character varying(50),
    commision_rate numeric NOT NULL DEFAULT 5,
    email character varying(150) NOT NULL,
    password_hash text NOT NULL,
    PRIMARY KEY (seller_id)
);

CREATE TABLE IF NOT EXISTS public.clients
(
    user_id bigserial NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(100) NOT NULL,
    password_hash character varying(500) NOT NULL,
    phone_number character varying(50),
    address1 character varying(255) NOT NULL,
    address2 character varying(255),
    city character varying(50) NOT NULL,
    state character varying(50) NOT NULL,
    country character varying(50) NOT NULL,
    zip_code character varying(20),
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.category
(
    category_id bigserial NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(500),
    PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id bigserial NOT NULL,
    name character varying(200) NOT NULL,
    description text NOT NULL,
    price numeric NOT NULL DEFAULT 0,
    inventory numeric NOT NULL DEFAULT 0,
    category_id bigint NOT NULL DEFAULT 0,
    seller_id bigint NOT NULL,
    PRIMARY KEY (product_id),
    UNIQUE (category_id),
    UNIQUE (seller_id)
);

CREATE TABLE IF NOT EXISTS public.product_image
(
    product_image_id bigserial NOT NULL,
    product_id bigint NOT NULL,
    url character varying(150) NOT NULL,
    alt character varying(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.recomendations
(
    recommendation_id bigserial NOT NULL,
    user_id bigint NOT NULL,
    product_id bigint NOT NULL,
    rating integer NOT NULL,
    commentary text,
    PRIMARY KEY (recommendation_id)
);

CREATE TABLE IF NOT EXISTS public.recomendations_products
(
    recomendations_product_id bigint NOT NULL,
    "Products_product_id" bigserial NOT NULL
);

CREATE TABLE IF NOT EXISTS public.recomendations_clients
(
    recomendations_user_id bigint NOT NULL,
    clients_user_id bigserial NOT NULL
);

CREATE TABLE IF NOT EXISTS public.orders
(
    order_id bigserial NOT NULL,
    client_id bigserial NOT NULL,
    status order_status NOT NULL DEFAULT 'Pending Payment',
    sub_total_cents numeric NOT NULL,
    tax_cents numeric NOT NULL,
    freight_cents numeric,
    currency bit varying(4)[] NOT NULL,
    created_at date NOT NULL,
    updated_at date,
    PRIMARY KEY (order_id)
);


CREATE TABLE IF NOT EXISTS public.orders_products
(
    orders_order_id bigserial NOT NULL,
    products_product_id bigserial NOT NULL,
    quantity numeric NOT NULL,
    PRIMARY KEY (orders_order_id, products_product_id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    payment_id bigserial NOT NULL,
    order_id bigint NOT NULL,
    payment_date date NOT NULL,
    amount numeric NOT NULL,
    payment_method character varying(50) NOT NULL,
    transaction_status payment_status NOT NULL DEFAULT 'Pending';
    PRIMARY KEY (payment_id),
    UNIQUE (order_id)
);

CREATE TYPE cart_status AS ENUM (
    'Active',
    'Abandoned',
    'Converted',
    'Expired'
);

CREATE TYPE order_status AS ENUM (
    'Pending Payment',     -- Waiting for financial confirmation (e.g., waiting for bank processing)
    'Payment Confirmed',   -- Payment approved; ready for inventory/picking
    'Payment Failed',      -- Transaction denied; customer must retry payment
    'Cancelled',           -- Order voided by the customer or system
    'Processing',          -- In storage: items are being picked and packed
    'Shipped',             -- Handed over to the carrier/shipping company
    'Out for Delivery',    -- At the local depot, on the final delivery route
    'Delivered',           -- Received by the customer
    'Completed',           -- Finalized status (delivered and post-sale period ended)
    'Returned'             -- Product has been returned by the customer
);

CREATE TYPE payment_status AS ENUM (
    'Pending',
    'Approved',
    'Failed',
    'Refunded',
    'Captured'
);

CREATE TABLE IF NOT EXISTS public.cart
(
    cart_id bigserial NOT NULL,
    user_id bigint NOT NULL,
    created_date date NOT NULL,
    updated_date date,
	status cart_status NOT NULL DEFAULT 'Active',
    PRIMARY KEY (cart_id)
);

CREATE TABLE IF NOT EXISTS public.cart_items
(
    cart_item bigserial NOT NULL,
    cart_id bigint NOT NULL,
    product_id bigint NOT NULL,
    quantity numeric NOT NULL,
    PRIMARY KEY (cart_item, quantity)
);



ALTER TABLE IF EXISTS public.products
    ADD FOREIGN KEY (category_id)
    REFERENCES public.category (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.products
    ADD FOREIGN KEY (seller_id)
    REFERENCES public.sellers (seller_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.product_image
    ADD FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.recomendations_products
    ADD FOREIGN KEY (recomendations_product_id)
    REFERENCES public.recomendations (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.recomendations_products
    ADD FOREIGN KEY ("Products_product_id")
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.recomendations_clients
    ADD FOREIGN KEY (recomendations_user_id)
    REFERENCES public.recomendations (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.recomendations_clients
    ADD FOREIGN KEY (clients_user_id)
    REFERENCES public.clients (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders_products
    ADD FOREIGN KEY (orders_order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders_products
    ADD FOREIGN KEY (products_product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.payments
    ADD FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cart
    ADD FOREIGN KEY (user_id)
    REFERENCES public.clients (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cart_items
    ADD FOREIGN KEY (cart_id)
    REFERENCES public.cart (cart_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cart_items
    ADD FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;



END;